project:
  type: website
  output-dir: docs

website:
  title: "Jiang Duo"
  # favicon: archive/site_images/Logo-INRAE.jpg
  navbar:
    search: false
    # logo: archive/site_images/Logo-INRAE.jpg
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - learning.qmd
      - papers.qmd
      - science.qmd

      
      
      # - group.qmd
      # - courses/index.qmd
      # - more/index.qmd


format:
  html:
    theme:
      light: [flatly, custom.scss, custom-light.scss]
      dark: [darkly, custom.scss, custom-dark.scss]
    css: styles.css
    toc: true



